import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// TypeScript: CSS imports need type declarations; add "src/global.d.ts" with
// 'declare module "*.css";' to avoid using @ts-ignore in the future.
// @ts-ignore
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Navbar from "@/components/layout/navbar";
import { NotificationCountProvider } from "@/hooks/use-notification-count";
import ThemeProvider from "@/components/layout/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider>
            <NotificationCountProvider>
              <div className="flex min-h-screen flex-col bg-background text-foreground">
                <Navbar />
                <main className="flex flex-1 flex-col">
                  <div className="mx-auto flex w-full max-w-6xl  flex-1 flex-col px-4 py-8 md:py-10">
                    {children}
                  </div>
                </main>
              </div>
              <Toaster />
            </NotificationCountProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}